#!/bin/bash

set -e

# Exit when gitleaks is not installed
if ! command -v gitleaks &> /dev/null; then
    echo "gitleaks is not installed. Aborting..." >&2
    exit 1
fi

# Run gitleaks to detect hardcoded secrets
gitleaks git --pre-commit --staged --no-banner --no-color --log-level error --verbose
gl=$?

# Exit if gitleaks found issues
if [[ ${gl} -ne 0 ]]; then
    exit ${gl}
fi

# Create a signature and a hash
GL_VER=$(gitleaks version)
TS=$(date --utc +%FT%T)
GL_SIGN=$(echo -n "${GL_VER}|${TS}" | base64)
GL_HASH=$(echo -n ${GL_SIGN}| sha1sum | awk '{print $1}')

# Be sure the variables are set
test -n "$GL_SIGN"
test -n "$GL_HASH"

# Store the data in a temp file to be added as a git msg
cat > .git/.gitleaks_data <<EOF
Gitleaks-Sign: ${GL_SIGN}
Gitleaks-Hash: ${GL_HASH}
EOF

exit 0
